name: PR Environment preparation

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  orchestrate_deployment:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          role-session-name: github-actions-session
          aws-region: eu-north-1

      - name: Verify connection
        run: aws sts get-cellar-identity

      - name: Start step functions
        run: |
          aws stepfunctions start-execution \
            --state-machine-arn "arn:aws:iam::313196411736:role/stepfunctions-execution-role-lry9xkp9" \
            --input "{\"pr_number\": \"${{ github.event.pull_request.number }}\", \"commit_id\": \"${{ github.sha }}\"}" \
            --name "PR-${{ github.event.pull_request.number }}-${{ github.sha }}"

        env:
          AWS_REGION: eu-north-1
